// <auto-generated />
using System;
using Ftw.Hotels.HotelCatalog.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ftw.Hotels.HotelCatalog.Data.Migrations
{
    [DbContext(typeof(HotelCatalogDbContext))]
    [Migration("20230103073556_hotels-rooms")]
    partial class hotelsrooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ftw.Hotels.HotelCatalog.Data.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e206904-5ce5-45c2-97c0-5c9aff34bf74"),
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("f42bec68-0475-4843-a16b-d4307acb80a3"),
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("337b4bfa-8906-4035-a0ef-260ec8034469"),
                            Code = "US",
                            Name = "United States of America"
                        });
                });

            modelBuilder.Entity("Ftw.Hotels.HotelCatalog.Data.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            City = "Brussels",
                            CountryId = new Guid("4e206904-5ce5-45c2-97c0-5c9aff34bf74"),
                            Description = "",
                            Latitude = 50.850346000000002,
                            Longitude = 4.3517210000000004,
                            Name = "Crown Resort & Spa",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            City = "Hasselt",
                            CountryId = new Guid("4e206904-5ce5-45c2-97c0-5c9aff34bf74"),
                            Description = "",
                            Latitude = 50.930691000000003,
                            Longitude = 5.3324800000000003,
                            Name = "Queen's Cosmos Motel",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            City = "Kortrijk",
                            CountryId = new Guid("4e206904-5ce5-45c2-97c0-5c9aff34bf74"),
                            Description = "",
                            Latitude = 50.827969000000003,
                            Longitude = 3.2649300000000001,
                            Name = "Historic Dune Resort",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            City = "Bruges",
                            CountryId = new Guid("4e206904-5ce5-45c2-97c0-5c9aff34bf74"),
                            Description = "",
                            Latitude = 51.209347000000001,
                            Longitude = 3.2246990000000002,
                            Name = "Prism Hotel",
                            Stars = 3
                        },
                        new
                        {
                            Id = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            City = "Osaka",
                            CountryId = new Guid("f42bec68-0475-4843-a16b-d4307acb80a3"),
                            Description = "",
                            Latitude = 34.693736999999999,
                            Longitude = 135.50216699999999,
                            Name = "Paragon Motel",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a98f77b5-4572-485f-b355-7f565238eca9"),
                            City = "Kyoto",
                            CountryId = new Guid("f42bec68-0475-4843-a16b-d4307acb80a3"),
                            Description = "",
                            Latitude = 35.021040999999997,
                            Longitude = 135.7556075,
                            Name = "Ruby Shores Hotel",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("c26bc1bd-9264-4d53-9c04-9e9a7aca7d0f"),
                            City = "Sakai",
                            CountryId = new Guid("f42bec68-0475-4843-a16b-d4307acb80a3"),
                            Description = "",
                            Latitude = 34.529124000000003,
                            Longitude = 135.50156000000001,
                            Name = "Sunset Legacy Hotel",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            City = "New York",
                            CountryId = new Guid("337b4bfa-8906-4035-a0ef-260ec8034469"),
                            Description = "",
                            Latitude = 40.7127281,
                            Longitude = -74.006015199999993,
                            Name = "Farmhouse Resort",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            City = "Washington",
                            CountryId = new Guid("337b4bfa-8906-4035-a0ef-260ec8034469"),
                            Description = "",
                            Latitude = 38.8950368,
                            Longitude = -77.036542699999998,
                            Name = "Eastern Willow Hotel",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            City = "Los Angeles",
                            CountryId = new Guid("337b4bfa-8906-4035-a0ef-260ec8034469"),
                            Description = "",
                            Latitude = 34.053690899999999,
                            Longitude = -118.242766,
                            Name = "Paradise Resort",
                            Stars = 3
                        },
                        new
                        {
                            Id = new Guid("b05df49e-1f60-4128-888f-4f5836cc043b"),
                            City = "Chicago",
                            CountryId = new Guid("337b4bfa-8906-4035-a0ef-260ec8034469"),
                            Description = "",
                            Latitude = 41.875561599999997,
                            Longitude = -87.6244212,
                            Name = "Antique Bay Spa",
                            Stars = 3
                        },
                        new
                        {
                            Id = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            City = "Dallas",
                            CountryId = new Guid("337b4bfa-8906-4035-a0ef-260ec8034469"),
                            Description = "",
                            Latitude = 32.776271899999998,
                            Longitude = -96.796855899999997,
                            Name = "Antique Cavern Hotel",
                            Stars = 4
                        });
                });

            modelBuilder.Entity("Ftw.Hotels.HotelCatalog.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("268ca2d2-2fd5-43a1-bf68-293f6ce33f31"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("93000f05-3afa-4c37-b0e7-2700efcd0612"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("d1f4ddd1-bf73-4722-a5ec-ebe11d12d727"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("ddbd2d96-4478-41d8-9d78-af6f3e688124"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("cd9f8074-fbe2-4902-b18d-abac2c15f864"),
                            Capacity = 4,
                            Floor = 2,
                            HotelId = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("e233b2be-4d01-4783-a05d-176688c00d9c"),
                            Capacity = 4,
                            Floor = 2,
                            HotelId = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("f8cc5d2c-be43-4870-badf-6c956fbdc4a0"),
                            Capacity = 2,
                            Floor = 3,
                            HotelId = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            Number = "301"
                        },
                        new
                        {
                            Id = new Guid("7d4ed052-bda2-4dfd-8b3e-13246bbafce0"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("2eb0d367-1fe6-4968-9d99-13cdf192b984"),
                            Number = "302"
                        },
                        new
                        {
                            Id = new Guid("6303cba9-a76e-4d2b-82b7-057fcccb36c1"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("1cef858b-5c87-4fdb-b997-752aa5dce2a2"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("b67a9def-f00c-4fd5-a934-b659c5f8ee03"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("06d8c1fe-7006-4383-aeb9-51b5a67880a7"),
                            Capacity = 5,
                            Floor = 1,
                            HotelId = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            Number = "104"
                        },
                        new
                        {
                            Id = new Guid("f67b4346-02d3-4c74-b679-99b99c13994a"),
                            Capacity = 4,
                            Floor = 1,
                            HotelId = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            Number = "105"
                        },
                        new
                        {
                            Id = new Guid("7230b419-7743-4546-9f48-aa97486d60b7"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            Number = "106"
                        },
                        new
                        {
                            Id = new Guid("6c7abc41-2099-4e6d-af1c-3fe563075404"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            Number = "107"
                        },
                        new
                        {
                            Id = new Guid("9a087c46-edfc-4d14-b628-c16baa4b2f08"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("1b43177a-c518-4b2a-909a-ee4fc84c6820"),
                            Number = "108"
                        },
                        new
                        {
                            Id = new Guid("e1046fdb-4f8d-4a50-9094-23e1dd369427"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("964ca8a8-7245-46af-ace8-e84d9079805f"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("ba39e5c2-b1fb-4e64-ad50-44a29f831416"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("0236ca82-afe0-4b35-9fcf-8fb3187a18bb"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "104"
                        },
                        new
                        {
                            Id = new Guid("829fa15f-e883-428b-8082-908c98380ac4"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "105"
                        },
                        new
                        {
                            Id = new Guid("1d582461-c165-457a-a834-57eb36fa6c92"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "106"
                        },
                        new
                        {
                            Id = new Guid("f401ed99-0bf5-4135-90b9-8b67f201965d"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "107"
                        },
                        new
                        {
                            Id = new Guid("82c9b20f-5304-4d53-8818-39af4ca5381d"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("cf7e4e6f-d46c-46ef-ab6c-e0d67d5e1eae"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("c51d6453-2de8-4a38-acf5-b243884990c6"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("51c84918-3a1c-48b7-9279-daf3efd0c336"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "204"
                        },
                        new
                        {
                            Id = new Guid("c20cac9f-b008-4dc2-9616-14d05833f3cf"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "205"
                        },
                        new
                        {
                            Id = new Guid("9e79c29e-6669-40b0-90e3-581de2e846aa"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "206"
                        },
                        new
                        {
                            Id = new Guid("e0a0fc8e-6ddf-42a8-b021-a6978664f794"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "207"
                        },
                        new
                        {
                            Id = new Guid("836f2785-cece-4489-8e31-a63a23a0f2bf"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "208"
                        },
                        new
                        {
                            Id = new Guid("0f0c36dd-90a6-498f-b3d2-5862336eddca"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("e7432cfd-41df-4b37-b641-c8dbf94328e1"),
                            Number = "209"
                        },
                        new
                        {
                            Id = new Guid("6479c299-b7f8-4023-98df-edb8c530fc34"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("89bac4c7-6879-4df3-a332-42887a2aa076"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("b9ebfecf-4299-4530-9853-4cef81a8fc2d"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("5c9b18b7-6f44-4c8d-9d2e-c491b6b38460"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("4ae69a56-a4ff-4416-8fd6-7c44c993af2b"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("759d2158-b840-4c4a-8ea2-3a404b38812e"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("0203c85b-2362-42a9-9feb-554edee237b8"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "301"
                        },
                        new
                        {
                            Id = new Guid("04dab6ae-b643-4b75-a12a-ee4644b1aa4a"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "302"
                        },
                        new
                        {
                            Id = new Guid("93e98279-415c-41ec-afe4-6b6181bed3c4"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "303"
                        },
                        new
                        {
                            Id = new Guid("d6aacec0-acf1-492b-80d1-2ac45edd6c8c"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "401"
                        },
                        new
                        {
                            Id = new Guid("7a3a8ee8-58f7-4c29-a924-e47adff5c4ff"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "402"
                        },
                        new
                        {
                            Id = new Guid("a57d1ec6-180b-480f-ba6b-245e18ecc019"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("23de6950-b9b6-426b-a892-503dc1942335"),
                            Number = "403"
                        },
                        new
                        {
                            Id = new Guid("841f6c53-d0f6-40b5-ba56-5bd40aa0127c"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("d61387b3-02dc-446c-922a-621e2d4a0a57"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("cb87c0f2-13cb-43ed-a245-18c576f7d711"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("f8266773-61a1-4888-8682-03b9b7f210df"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "104"
                        },
                        new
                        {
                            Id = new Guid("247c1e4f-c5cf-47b3-afac-58e2c95de7ff"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "105"
                        },
                        new
                        {
                            Id = new Guid("be837b05-891f-4304-9e6d-b48a87001494"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "106"
                        },
                        new
                        {
                            Id = new Guid("672487eb-15bd-469c-99af-ee16c5b94a85"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("4245db33-d186-4cbb-8f16-51bcfdfaa184"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("6faed1cf-cced-4a68-b856-88c3e6ee3b82"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("305f6f57-7575-48f9-9b7a-69331d9f2f24"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "204"
                        },
                        new
                        {
                            Id = new Guid("a8c07a37-66b4-4ba5-aad4-3ee60605e52e"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "205"
                        },
                        new
                        {
                            Id = new Guid("4d205fdc-5683-467c-a9b0-298549929804"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "206"
                        },
                        new
                        {
                            Id = new Guid("45941394-d096-49f1-b9c4-f80d37551999"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "207"
                        },
                        new
                        {
                            Id = new Guid("bb2ab1f8-8740-4428-be85-e4d684d29a33"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("3a4287d1-8df6-4cf9-92de-6dfe7f094035"),
                            Number = "208"
                        },
                        new
                        {
                            Id = new Guid("6fe8fe67-80b5-44a2-a674-e54f8b30274c"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("a98f77b5-4572-485f-b355-7f565238eca9"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("da5b3fe3-6d72-4833-a9ce-a363c597fb97"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("a98f77b5-4572-485f-b355-7f565238eca9"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("10ca8d19-1dda-443f-be80-7c7c2efba499"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("a98f77b5-4572-485f-b355-7f565238eca9"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("6499a01f-fc7d-4ed2-bf4b-08e089977909"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("a98f77b5-4572-485f-b355-7f565238eca9"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("2828863c-f340-4631-ac60-151cc274f707"),
                            Capacity = 4,
                            Floor = 2,
                            HotelId = new Guid("a98f77b5-4572-485f-b355-7f565238eca9"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("338f21eb-4808-40fb-ba0a-9f81d4773e87"),
                            Capacity = 4,
                            Floor = 2,
                            HotelId = new Guid("a98f77b5-4572-485f-b355-7f565238eca9"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("25c28785-a085-44a2-9462-08824c040d32"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("c26bc1bd-9264-4d53-9c04-9e9a7aca7d0f"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("61e19d6f-4a69-4621-bda3-c47d7c2614bb"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("c26bc1bd-9264-4d53-9c04-9e9a7aca7d0f"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("9c19afaa-803a-4fb5-b213-d9ac6803edfd"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("c26bc1bd-9264-4d53-9c04-9e9a7aca7d0f"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("1b119065-e85f-413b-b4e3-ae3d17363617"),
                            Capacity = 5,
                            Floor = 1,
                            HotelId = new Guid("c26bc1bd-9264-4d53-9c04-9e9a7aca7d0f"),
                            Number = "104"
                        },
                        new
                        {
                            Id = new Guid("9599adc6-61c9-41c8-915f-58d4c7f2e98c"),
                            Capacity = 4,
                            Floor = 1,
                            HotelId = new Guid("c26bc1bd-9264-4d53-9c04-9e9a7aca7d0f"),
                            Number = "105"
                        },
                        new
                        {
                            Id = new Guid("8bbe50f3-9cf4-41ee-b46b-d2ec1fa3d5a9"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("c26bc1bd-9264-4d53-9c04-9e9a7aca7d0f"),
                            Number = "106"
                        },
                        new
                        {
                            Id = new Guid("52150feb-4bf2-4818-a0a3-2e85580c5d59"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("89d63328-9b59-4ddc-8485-41d33974bc81"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("97cbf9e4-d22f-4230-a607-32368fc95da2"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("07894cbb-397e-4c84-9a16-5184385f3d0a"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("640f1940-7a07-4322-a99a-2285d5bf1c21"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("7db92a1e-9a8f-43f9-931c-97bbcf24e355"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("cfba9831-0f96-4985-940e-70a655d13876"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "301"
                        },
                        new
                        {
                            Id = new Guid("d65b6ff4-8bdc-4aea-9b35-a3cfed9b1483"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "302"
                        },
                        new
                        {
                            Id = new Guid("4a682304-8272-4493-8225-97fb258f389c"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "303"
                        },
                        new
                        {
                            Id = new Guid("b8047f8a-9ceb-4b55-927d-cffb9e5cada2"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "401"
                        },
                        new
                        {
                            Id = new Guid("3a38ebdb-7ef3-47a8-8501-ca361c3dcde8"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "402"
                        },
                        new
                        {
                            Id = new Guid("648ebe68-0f73-4cb1-a8a5-668d5546c1aa"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("1ba6d3a7-beae-4745-b818-e62e150fbb0b"),
                            Number = "403"
                        },
                        new
                        {
                            Id = new Guid("b5c02714-d709-46c5-b0f5-82cd40c8815b"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("7a70bed3-1d82-4e34-8c13-1ea95f016639"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("0c9aeddd-87a2-4f6d-9c01-766d55f8d14c"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("bc3e74d0-8f36-486a-87fb-9e0d34d3c202"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "104"
                        },
                        new
                        {
                            Id = new Guid("0401b525-45fe-4c75-992d-10adcd4cef60"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "105"
                        },
                        new
                        {
                            Id = new Guid("3b41d3c9-3eb7-4ff8-b40b-e8edd3fe0795"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "106"
                        },
                        new
                        {
                            Id = new Guid("760a5317-35ee-440d-81a5-745dc5995f45"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "107"
                        },
                        new
                        {
                            Id = new Guid("fa6b67c0-2c7f-4db6-a7f4-43883471dfbe"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("92470ca6-a55b-4662-b053-260ec99a1eee"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("df5e5c52-6799-4052-a306-3fc67347443a"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("593eec4d-81d5-43b0-abf7-7577cb30495e"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "204"
                        },
                        new
                        {
                            Id = new Guid("b5f0b3a3-23c6-4e44-b551-65ee5e5e8102"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "205"
                        },
                        new
                        {
                            Id = new Guid("e8716a6a-83b0-48b0-8bcd-4385f31f58c0"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "206"
                        },
                        new
                        {
                            Id = new Guid("962b2d27-e389-4513-9c12-1c3656cd8258"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "207"
                        },
                        new
                        {
                            Id = new Guid("3b79559c-d8ca-4c03-aeac-831fed4cc055"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "208"
                        },
                        new
                        {
                            Id = new Guid("6b6e7865-95f8-4170-8c6f-e23e6b751b7f"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("0a9fa4b3-a2d2-4455-b61c-c471adbc3bd3"),
                            Number = "209"
                        },
                        new
                        {
                            Id = new Guid("258d4c97-f2b6-4542-8cbc-1aa193cba708"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("2cc778a8-1c37-4b11-a6a3-be4e4a759a61"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("1adbfe2a-25b3-4dd6-b2de-78d8588cd0f6"),
                            Capacity = 1,
                            Floor = 1,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("73bd48b4-7884-4459-b658-338d0679cc01"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("f31b366f-d359-4e4e-ada6-e6e8f75ad737"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("65d90003-979d-49a3-98d8-2cd157dcda6b"),
                            Capacity = 1,
                            Floor = 2,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("99baa070-27ad-44fa-a302-fd1f4c5b1bec"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "301"
                        },
                        new
                        {
                            Id = new Guid("3236355d-8f3b-4745-9239-0059bccbceec"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "302"
                        },
                        new
                        {
                            Id = new Guid("8dc91a10-06d1-4abb-861f-6ada4089e98c"),
                            Capacity = 1,
                            Floor = 3,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "303"
                        },
                        new
                        {
                            Id = new Guid("fd13abe4-838f-46ec-b3c3-3348cde71487"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "401"
                        },
                        new
                        {
                            Id = new Guid("66de7dcc-856b-4a58-8062-300dab4269c9"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "402"
                        },
                        new
                        {
                            Id = new Guid("700e3dda-3a9e-48cb-b57b-852929837818"),
                            Capacity = 1,
                            Floor = 4,
                            HotelId = new Guid("88e473f7-8048-465b-ad3b-9f711c6fba82"),
                            Number = "403"
                        },
                        new
                        {
                            Id = new Guid("1078d6d9-76db-4fe9-b14f-338df0ca4337"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("b05df49e-1f60-4128-888f-4f5836cc043b"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("8d8d378a-40e0-4022-abe4-23462293fc96"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("b05df49e-1f60-4128-888f-4f5836cc043b"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("f3180f39-3869-4de2-8910-d53ced60ce24"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("b05df49e-1f60-4128-888f-4f5836cc043b"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("ad57fa94-050b-43a5-9105-8916ec3671aa"),
                            Capacity = 5,
                            Floor = 1,
                            HotelId = new Guid("b05df49e-1f60-4128-888f-4f5836cc043b"),
                            Number = "104"
                        },
                        new
                        {
                            Id = new Guid("67302c16-9d04-4e1a-a3ca-59686a8c9284"),
                            Capacity = 4,
                            Floor = 1,
                            HotelId = new Guid("b05df49e-1f60-4128-888f-4f5836cc043b"),
                            Number = "105"
                        },
                        new
                        {
                            Id = new Guid("bb4d13f0-f69c-41c1-b346-9f564d7aabc8"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("b05df49e-1f60-4128-888f-4f5836cc043b"),
                            Number = "106"
                        },
                        new
                        {
                            Id = new Guid("68c66403-7d68-4919-8bbf-0d39969ffd87"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("fbde0d19-5a64-4716-8f2a-ebe60c2075a1"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("cc9c982c-8fb7-4124-873d-b69ff3456a44"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("b8289abf-943d-4754-b535-0c8b30f656d1"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "104"
                        },
                        new
                        {
                            Id = new Guid("93693c4c-dead-4395-8fac-cfd3c63404d3"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "105"
                        },
                        new
                        {
                            Id = new Guid("3faef830-ff98-486f-8db2-5b820a8f5712"),
                            Capacity = 2,
                            Floor = 1,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "106"
                        },
                        new
                        {
                            Id = new Guid("8ce6f406-95f7-4744-a110-f9e52c3114dd"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("deef57ea-7770-4cb3-86e3-c0260936ca8e"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("4d2fff97-68a5-4ea6-9d4b-a0a0c3f689ec"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("53300253-ddc0-4394-ada8-666d77bd080f"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "204"
                        },
                        new
                        {
                            Id = new Guid("deec06df-c9ab-4ed1-af3e-0cb8463512ea"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "205"
                        },
                        new
                        {
                            Id = new Guid("ec07ab88-57f7-4c6a-b366-3a5a52be055c"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "206"
                        },
                        new
                        {
                            Id = new Guid("c12bf98d-77b2-4835-a5c3-91fd3234755d"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "207"
                        },
                        new
                        {
                            Id = new Guid("612b2d89-3067-4e4c-b801-777889ff6985"),
                            Capacity = 2,
                            Floor = 2,
                            HotelId = new Guid("fbf4e4dc-c068-472c-8feb-d809384c3af8"),
                            Number = "208"
                        });
                });

            modelBuilder.Entity("Ftw.Hotels.HotelCatalog.Data.Models.Hotel", b =>
                {
                    b.HasOne("Ftw.Hotels.HotelCatalog.Data.Models.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Ftw.Hotels.HotelCatalog.Data.Models.Room", b =>
                {
                    b.HasOne("Ftw.Hotels.HotelCatalog.Data.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Ftw.Hotels.HotelCatalog.Data.Models.Country", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("Ftw.Hotels.HotelCatalog.Data.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
