on:
  workflow_dispatch:
    
  pull_request:
    branches: 
    - main
    paths: 
    - src/hotels-app
    
name: CI-CD | Hotels App
jobs:
      
  app-dotnet-ci:
    name: Build
    uses: ./.github/workflows/template-app-dotnet-ci.yml
    with:
      SOLUTION_FOLDER: src/hotels-app
      
  app-docker-ci-catalog:
    name: Catalog
    uses: ./.github/workflows/template-app-docker-ci.yml
    needs: app-dotnet-ci
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.HotelCatalog/Dockerfile
      DOCKER_IMAGE_NAME: ftw-hotel-catalog
      DOCKER_VERSION: 0.1
      
  app-docker-ci-booking:
    name: Booking
    uses: ./.github/workflows/template-app-docker-ci.yml
    needs: app-dotnet-ci
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.HotelBooking/Dockerfile
      DOCKER_IMAGE_NAME: ftw-hotel-booking
      DOCKER_VERSION: 0.1

  app-docker-ci-pricing:
    name: Pricing
    uses: ./.github/workflows/template-app-docker-ci.yml
    needs: app-dotnet-ci
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.HotelPricing/Dockerfile
      DOCKER_IMAGE_NAME: ftw-hotel-pricing
      DOCKER_VERSION: 0.1
      
  app-docker-ci-supergraph:
    name: Supergraph
    uses: ./.github/workflows/template-app-docker-ci.yml
    needs: app-dotnet-ci
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.SuperGraph/Dockerfile
      DOCKER_IMAGE_NAME: ftw-hotel-supergraph
      DOCKER_VERSION: 0.1
