on:
  workflow_dispatch:
    
  pull_request:
    branches: 
    - main
    paths: 
    - src/hotels-app
    
name: CI-CD | Hotels App
jobs:
  app-dotnet-ci:
    name: Build
    uses: ./.github/workflows/template-app-dotnet-ci.yml
    with:
      SOLUTION_FOLDER: src/hotels-app
          
  
