on:
  workflow_dispatch:
    
  pull_request:
    branches: 
    - main
    paths: 
    - src/real-estate-app/**
    
  push:
    branches: 
    - main
    paths: 
    - src/real-estate-app/**
    
name: CI-CD | Real Estate App
jobs: 
  app-ci-config:
    name: Config
    uses: ./.github/workflows/template-app-ci-config.yml
    
  app-ci-dotnet-sales:
    name: Build
    uses: ./.github/workflows/template-app-ci-dotnet.yml
    with:
      BUILD_FOLDER: src/real-estate-app/Ftw.RealEstate.Sales
      
  app-cd-sales-dev:
    name: DEV Sales
    uses: ./.github/workflows/template-app-cd-app-service.yml
    needs: [app-ci-config, app-ci-dotnet-sales]
    with:
      ENVIRONMENT_NAME: dev
      RESOURCE_GROUP_NAME: ftw-dev-real-estate-app-rg
      APP_SERVICE_NAME: ftw-dev-real-estate-sales-wapp
      PUBLISH_TO_APIM: false
    secrets: inherit
