on:
  workflow_dispatch:
    
  pull_request:
    branches: 
    - main
    paths: 
    - infra
    
name: CI-CD | Infra
jobs:
  infra-ci:
    name: Build
    uses: ./.github/workflows/template-infra-ci.yml
          
  infra-cd-dev:
    name: DEV
    uses: ./.github/workflows/template-infra-cd.yml
    needs: infra-ci
    with:
      ENVIRONMENT_NAME: dev
      ENVIRONMENT_KEY: dev
    secrets: inherit
