on:
  workflow_dispatch:
    
  pull_request:
    branches: 
    - main
    paths: 
    - src/hotels-app
    
name: CI-CD | Hotels App
jobs:               
  app-docker-ci-catalog:
    name: Catalog CI
    uses: ./.github/workflows/template-app-ci-docker.yml
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.HotelCatalog/Dockerfile
      IMAGE_NAME: ftw-hotel-catalog
      
  app-container-app-cd-catalog-dev:
    name: Catalog CD
    uses: ./.github/workflows/template-app-cd-container-app.yml
    needs: app-docker-ci-catalog
    with:
      IMAGE_NAME: ftw-hotel-catalog
      IMAGE_VERSION: ${{ needs.app-docker-ci-catalog.outputs.IMAGE_VERSION }}
      ENVIRONMENT_NAME: dev
      RESOURCE_GROUP_NAME: ftw-dev-app-hotels-rg
      CONTAINER_APP_NAME: ftw-dev-hotel-catalog-capp
      CONTAINER_REGISTRY_NAME: ftwdevapphotelsacr
    secrets: inherit
    
