on:
  workflow_dispatch:
    
  pull_request:
    branches: 
    - main
    paths: 
    - src/hotels-app/**
    
  push:
    branches: 
    - main
    paths: 
    - src/hotels-app/**
    
name: CI-CD | Hotels App
jobs: 
  configuration:
    name: CI Configuration
    runs-on: windows-latest
    steps:
      
  
