on:
  workflow_dispatch:
    
  pull_request:
    branches: 
    - main
    paths: 
    - src/hotels-app/**
    
  push:
    branches: 
    - main
    paths: 
    - src/hotels-app/**
    
name: CI-CD | Hotels App
jobs: 
  configuration:
    name: CI Configuration
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        
      - name: Rename configuration folder
        shell: pwsh
        run: |
          Rename-Item -Path "infra/05_configuration" -NewName "configuration"
        
      - name: Publish config artifact
        uses: actions/upload-artifact@v3
        with:
          name: config
          path: |
            infra/infra-parameters.json
            infra/configuration/api-management/apis
