on:
  workflow_call:
    inputs:
      #Mandatory inputs
      ENVIRONMENT_NAME:
        type: string
        required: true
      ENVIRONMENT_KEY:
        type: string
        required: true
        
      #Optional inputs
      INFRA_ARTIFACT_NAME:
        type: string
        default: infra
      RUNNER_NAME:
        type: string
        default: windows-latest

permissions:
  id-token: write
  contents: read
        
name: infra-deploy
jobs: 
  deploy-infra:
    name: Deploy Infra
    runs-on: ${{ inputs.RUNNER_NAME }}
    environment: ${{ inputs.ENVIRONMENT_NAME }}
    steps:
      - name: Download infra artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ${{ inputs.INFRA_ARTIFACT_NAME }}
          path: artifacts/infra
          
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: 32947824-3a40-4ef0-b140-8130b2df4d03 ##${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: 76213625-0893-4593-b9fc-c4568c5c1661 ##${{ secrets.AZURE_TENANT_ID }}
          subscription-id: 99da81c1-72ed-4a56-8c96-f360dbd22610 ##${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          
      - name: Deploy infra with Bicep
        shell: pwsh
        working-directory: artifacts/infra
        run: |
          .\deploy.ps1 -EnvironmentName ${{ inputs.ENVIRONMENT_NAME }} -EnvironmentKey ${{ inputs.ENVIRONMENT_KEY }} 
