on:
  workflow_call:
    inputs:
      INFRA_FOLDER:
        type: string
        default: infra
      BICEP_FILE_NAME:
        type: string
        default: infra.bicep  
      INFRA_ARTIFACT_NAME:
        type: string
        default: infra
     

name: infra-build
jobs: 
  build-infra:
    name: Build Infra
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: Validate Bicep
        shell: pwsh
        working-directory: ${{ inputs.INFRA_FOLDER }}
        run: |
          az bicep build --file ${{ inputs.BICEP_FILE_NAME }}  
          
      - name: Upload infra artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ inputs.INFRA_ARTIFACT_NAME }}
          path: ${{ inputs.INFRA_FOLDER }}
