on:
  workflow_dispatch:
    
  pull_request:
    branches: 
    - main
    paths: 
    - infra
name: infra-build
jobs: 
  build:
    name: Build Infra
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Validate Bicep
        shell: pwsh
        working-directory: infra
        run: |
          az bicep build --file infra.bicep   
