on:
  workflow_call:
    inputs:
      #Mandatory inputs
      DOCKER_FILE_PATH:
        type: string
        required: true
      IMAGE_NAME:
        type: string
        required: true
      IMAGE_VERSION:
        type: string
        required: true
        
      #Optional inputs
      DOCKER_ARTIFACT_NAME:
        type: string
        default: docker
      RUNNER_NAME:
        type: string
        default: ubuntu-latest
        
permissions:
  id-token: write
  contents: read

name: _template-app-ci-docker
jobs: 
  build-app:
    name: Build Docker
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
            
      - name: Build Docker image
        run: |
          docker build --tag ${{ inputs.IMAGE_NAME }}:${{ steps.gitversion.outputs.semVer }} --file ${{ inputs.DOCKER_FILE_PATH }} --platform linux/amd64 .    
          docker image save ${{ inputs.IMAGE_NAME }}:${{ steps.gitversion.outputs.semVer }} --output ${{ inputs.IMAGE_NAME }}.tar
           
      - name: Publish docker artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.DOCKER_ARTIFACT_NAME }}
          path: ${{ inputs.IMAGE_NAME }}.tar
