on:
  workflow_call:
    inputs:
      #Mandatory inputs
      ENVIRONMENT_NAME:
        type: string
        required: true
      RESOURCE_GROUP_NAME:
        type: string
        required: true
      APP_SERVICE_NAME:
        type: string
        required: true
        
      #Optional inputs
      PUBLISH_TO_APIM:
        type: boolean
        default: false
      APIM_API_ALIAS:
        type: string
        default: none
      RUNNER_NAME:
        type: string
        default: ubuntu-latest
      APP_ARTIFACT_NAME:
        type: string
        default: app
      CONFIG_ARTIFACT_NAME:
        type: string
        default: config
      
permissions:
  id-token: write
  contents: read
        
name: _template-app-cd-container-app
jobs: 
  deploy-container-app:
    name: Deploy Container App
    runs-on: ${{ inputs.RUNNER_NAME }}
    environment: ${{ inputs.ENVIRONMENT_NAME }}
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ${{ inputs.APP_ARTIFACT_NAME }}
          path: artifacts/app
      
      - name: Download config artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ${{ inputs.CONFIG_ARTIFACT_NAME }}
          path: artifacts/config
          
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
      
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: {{ inputs.APP_SERVICE_NAME }}
          package: artifacts/app
          
      - name: Upsert API in API Management
        if: ${{ inputs.PUBLISH_TO_APIM }}
        working-directory: artifacts/config/configuration/api-management/apis/${{ inputs.APIM_API_ALIAS }}
        shell: pwsh
        run: |
          $apiDefinitionUrl = "https://$((az webapp show --name ${{ inputs.APP_SERVICE_NAME }} --resource-group ${{ inputs.RESOURCE_GROUP_NAME }} | ConvertFrom-Json).enabledHostNames[0])/graphql"
          .\deploy.ps1 -ApiVersion v1 -ApiDefinitionUrl $apiDefinitionUrl -EnvironmentName ${{ inputs.ENVIRONMENT_NAME }} -EnvironmentKey ${{ inputs.ENVIRONMENT_NAME }} 
