on:
  workflow_call:
    inputs:
      #Mandatory inputs
      DOCKER_FILE_PATH:
        type: string
        required: true
      DOCKER_IMAGE_NAME:
        type: string
        required: true
      DOCKER_VERSION:
        type: string
        required: true
      ACR_NAME:
        type: string
        required: true
        
      #Optional inputs
      ENVIRONMENT_NAME:
        type: string
        default: dev
      RUNNER_NAME:
        type: string
        default: windows-latest
        
permissions:
  id-token: write
  contents: read

name: _app-docker-ci-template
jobs: 
  build-app:
    name: Build Docker
    runs-on: ${{ inputs.RUNNER_NAME }}
    environment: ${{ inputs.ENVIRONMENT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3       
      
      - name: Build Docker image
        run: |
          docker build --tag ${{ inputs.ACR_NAME }}.azurecr.io/${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.DOCKER_VERSION }} --file ${{ inputs.DOCKER_FILE_PATH }} .

      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          
      - name: Publish image to ACR
        run: |
          az acr login --name ${{ inputs.ACR_NAME }}
          docker push ${{ inputs.ACR_NAME }}.azurecr.io/${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.DOCKER_VERSION }}
