on:
  workflow_call

name: _template-add-hotels-ci
jobs:               
  app-docker-ci-catalog:
    name: Catalog CI
    uses: ./.github/workflows/template-app-ci-docker.yml
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.HotelCatalog/Dockerfile
      IMAGE_NAME: ftw-hotel-catalog
      
  app-docker-ci-booking:
    name: Booking CI
    uses: ./.github/workflows/template-app-ci-docker.yml
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.HotelBooking/Dockerfile
      IMAGE_NAME: ftw-hotel-booking
  
  app-docker-ci-pricing:
    name: Pricing CI
    uses: ./.github/workflows/template-app-ci-docker.yml
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.HotelPricing/Dockerfile
      IMAGE_NAME: ftw-hotel-pricing
      
  app-docker-ci-supergraph:
    name: SuperGraph CI
    uses: ./.github/workflows/template-app-ci-docker.yml
    with:
      DOCKER_FILE_PATH: src/hotels-app/Ftw.Hotels.SuperGraph/Dockerfile
      IMAGE_NAME: ftw-hotel-supergraph
