on:
  workflow_call:
    inputs:
      #Optional inputs
      INFRA_FOLDER:
        type: string
        default: infra
      BICEP_FILE_NAME:
        type: string
        default: infra.bicep  
      INFRA_ARTIFACT_NAME:
        type: string
        default: infra
      RUNNER_NAME:
        type: string
        default: windows-latest

name: _infra-ci-template
jobs: 
  build-infra:
    name: Build Infra
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3       
        
      - name: Validate Bicep
        shell: pwsh
        working-directory: ${{ inputs.INFRA_FOLDER }}
        run: |
          az bicep build --file ${{ inputs.BICEP_FILE_NAME }}  
          
      - name: Upload infra artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ inputs.INFRA_ARTIFACT_NAME }}
          path: ${{ inputs.INFRA_FOLDER }}
