on:
  workflow_call:
    inputs:
      #Optional inputs
      BUILD_FOLDER:
        type: string
        default: src
      BUILD_ARTIFACT_NAME:
        type: string
        default: app
      RUNNER_NAME:
        type: string
        default: ubuntu-latest

name: _template-app-ci-dotnet
jobs: 
  build-app:
    name: Build App
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3       
        
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ inputs.BUILD_FOLDER }}
        
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ inputs.BUILD_FOLDER }}
          
      - name: Test solution
        run: dotnet test --no-restore --verbosity normal
        working-directory: ${{ inputs.BUILD_FOLDER }}
      
      - name: Publish solution
        run: dotnet publish --configuration Release --no-restore --output ./output
        working-directory: ${{ inputs.BUILD_FOLDER }}
        
      - name: Publish solution artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.BUILD_ARTIFACT_NAME }}
          path: ${{ inputs.BUILD_FOLDER }}/output
